version: "3.9"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: bitly
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
  server:
    build: ./server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network
  client:
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
